#! /usr/bin/python3

import os
import pickle
import socket
import sys

def main():
    _, cmd, port = sys.argv
    sock = socket.socket()
    sock.connect(('', int(port)))
    sock.send(pickle.dumps((os.getcwd(), cmd)))
    sock.close()

if __name__ == "__main__":
    main()

